services:
  api:
    build: .
    container_name: life365_product_ai_api
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
    volumes:
      - ./:/app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
